parameters:
    elastic_apm:
        enabled: true
        appName: ~ #Name of this application, Required

services:
    elastic_apm.listener.request:
        class: Goksagun\ElasticApmBundle\EventListener\RequestListener
        arguments:
            - '%elastic_apm%'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 31 }
            - { name: kernel.event_listener, event: kernel.terminate, method: onKernelTerminate, priority: -2048 }

    elastic_apm.listener.exception:
        class: Goksagun\ElasticApmBundle\EventListener\ExceptionListener
        arguments:
            - '%elastic_apm%'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 32 }
